name: cienfuegos_folklore
description: "A Flutter project made by Alexis Manuel Hurtado Garcia, dev of Alabbi S.U.R.L."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/audio/
